### ISSUE TITLE
Issue with offline installation: importing gives syntax error

### ISSUE THREAD

**Issue by haykp** [alexforencich/cocotbext-pcie#12]
We were able to download package and install offline mode. 
When doing pip3 list it shows that cocotb-pcie is installed:

```
**/Python-3.9.6/bin/pip3 list
Package        Version
-------------- ----------
cocotb         1.6.0.dev0
cocotb-bus     0.0.0
cocotbext-axi  0.1.13
cocotbext-pcie 0.1.15
electrical     1.0.0
more-itertools 8.8.0
pip            21.1.3
setuptools     56.0.0
simulator      1.0.3
version        0.1.2
```
However when importing in python, it gives strange error:

```
python3
Python 3.9.6 (default, Aug  5 2021, 10:07:49) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cocotbext-pcie
  File "<stdin>", line 1
    import cocotbext-pcie
                    ^
SyntaxError: invalid syntax
```

Any ideas what is this?

**Comment by alexforencich** [comment]
It's a name space package. Import it as cocotbext.pcie.

**Comment by haykp** [comment]
Same error is there:
```
> import cocotbext.pcie
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cocotbext'

```

**Comment by alexforencich** [comment]
That's not the same error, it's no longer a syntax error.  Looks like you don't actually have the package installed.  Do you possibly have multiple python installations?

**Comment by haykp** [comment]
actually no, so strange.
The package installation passed good

**Comment by alexforencich** [comment]
well, in that case I have no idea what the issue is.  You should be able to import that, though:

    $ python
    Python 3.9.6 (default, Jun 30 2021, 10:22:16) 
    [GCC 11.1.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cocotbext.pcie
    >>>
